= Software guide

== Setup

Software uses Python 3.9.

Segmentation module installation:
```
cd segment_module
pip install .
```

To install all other dependencies:
```
pip install -r requirements.txt
```

To run the code:
```
cd software
python3.9 main.py
```

To turn referee commands on/of change the value of ref_enabled variable in main.py. +
If you wish to use the remote (XBox One S controller), just turn it on, if you feel a little vibration from the controller, it is connected to the NUC. Then you can run main.py and use the controller. +

* Use the controller sticks to move the robot.
* X changes between autonomous and remote controller mode
* Y switches the basket being targeted
* B closes the program
* Right Trigger can be used to activate the eating servo and the thrower motor

== Overview of Files

*camera.py* +
Contains and handles the realsense camera object.

*config_colors.py* +
File for interactive colour calibration. This file should be run to configure colours.

*gamepad.py* +
Handles communication with the Xbox Controller.

*image_processor.py* +
Handles all aspects of image processing, for example ball detection, basket detection and line calculations.

*main.py* +
The main game logic file, this should be run to activate the robot.

*mainboard.py* +
Handles communication between the robot mainboard and the main code.

*ref_cmd.py* +
Referee command handling and connecting to to the specified referee server.

*robot_utilities.py* +
Miscellaneous utility classes and functions, houses the logging functionality and sigmoid controller.
