title = "default_config"

[logic]
debug = false
state = 1 # WAIT: 1, START_WAIT: 3, CALIB_INPUT: 9,
basket = 1 # MAGENTA: 1, BLUE: 2

[referee]
enabled = true
robot_name = "OWO"
ip = "192.168.3.19"
port = "8222"

[logger]
print_enabled = true
file_enabled = true

[manual]
port = '/dev/input/event12'

[mainboard]
wheel_angles = [240, 120, 0]
encoder_edges_per_motor_revolution = 64
gearbox_ratio = 18.75
wheel_radius = 0.365 # meters
wheel_distance_from_center = 0.15 #meters
pid_control_frequency = 60 #Hz
max_speed = 15
hwid = "USB VID:PID=0483:5740"
baud_rate = 115200
r_const = 5
y_const = 1